Repository bazelbuild/rules_kotlin, pull requests merged in 2021-07, with the labels that each got.

#552 Use builtin targets for Bazel protos
  kotlin/internal/repositories/http_java_proto_file.bzl
  kotlin/internal/repositories/setup.bzl
  src/main/protobuf/BUILD
Labels: P2, component: common, status: closed - fixed, type: cleanup

#545 Use current java_stub_template
  kotlin/internal/repositories/release_repositories.bzl
  kotlin/internal/repositories/versions.bzl
Labels: P1, component: jvm, status: closed - fixed, type: bug

#541 Add the plugins examples to run in CI
  .bazelci/presubmit.yml
  examples/plugin/WORKSPACE
  examples/plugin/src/allopen/BUILD
  examples/plugin/src/allopennoarg/BUILD
  examples/plugin/src/noarg/BUILD
  examples/plugin/src/parcelize/BUILD
  examples/plugin/src/sam_with_receiver/BUILD
  examples/plugin/src/serialization/BUILD
Labels: P2, component: common, status: in review, type: cleanup
